
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./...
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
      - "386"

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc

  groups:
    - title: "New Features"
      regexp: "^feat[(\w+)]*:"
      order: 0
    - title: "Bug Fixes"
      regexp: "^fix[(\w+)]*:"
      order: 1
    -title: "Breaking Changes"
      regexp: "^BREAKING[(\w+)]*:"
      order: 2
    -title: "Other Changes"
      regexp: "^chore[(\w+)]*:"
      order: 3
    - title: "Documentation"
      regexp: "^docs[(\w+)]*:"
      order: 4
  filters:
    exclude:
      - "merge"
      - "Initial commit"
release:
  footer: >-
    This release was generated by [Winter](https://github.com/dizziedbliss/winter).